HW 1
================
Nathalie Fadel
2/19/2019

``` r
library(caret)
library(boot)
library(tidyverse)
library(ISLR)
library(glmnet)
library(corrplot)
library(plotmo)
library(glmnetUtils)
library(pls)
```

Import data
-----------

``` r
sol_test = read_csv("data/solubility_test.csv") #test data
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_integer(),
    ##   MolWeight = col_double(),
    ##   NumAtoms = col_double(),
    ##   NumNonHAtoms = col_double(),
    ##   NumBonds = col_double(),
    ##   NumNonHBonds = col_double(),
    ##   NumMultBonds = col_double(),
    ##   NumRotBonds = col_double(),
    ##   NumDblBonds = col_double(),
    ##   NumAromaticBonds = col_double(),
    ##   NumHydrogen = col_double(),
    ##   NumCarbon = col_double(),
    ##   NumNitrogen = col_double(),
    ##   NumOxygen = col_double(),
    ##   NumSulfer = col_double(),
    ##   NumChlorine = col_double(),
    ##   NumHalogen = col_double(),
    ##   NumRings = col_double(),
    ##   HydrophilicFactor = col_double(),
    ##   SurfaceArea1 = col_double(),
    ##   SurfaceArea2 = col_double()
    ##   # ... with 1 more columns
    ## )

    ## See spec(...) for full column specifications.

``` r
sol_train = read_csv("data/solubility_train.csv") #training data
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_integer(),
    ##   MolWeight = col_double(),
    ##   NumAtoms = col_double(),
    ##   NumNonHAtoms = col_double(),
    ##   NumBonds = col_double(),
    ##   NumNonHBonds = col_double(),
    ##   NumMultBonds = col_double(),
    ##   NumRotBonds = col_double(),
    ##   NumDblBonds = col_double(),
    ##   NumAromaticBonds = col_double(),
    ##   NumHydrogen = col_double(),
    ##   NumCarbon = col_double(),
    ##   NumNitrogen = col_double(),
    ##   NumOxygen = col_double(),
    ##   NumSulfer = col_double(),
    ##   NumChlorine = col_double(),
    ##   NumHalogen = col_double(),
    ##   NumRings = col_double(),
    ##   HydrophilicFactor = col_double(),
    ##   SurfaceArea1 = col_double(),
    ##   SurfaceArea2 = col_double()
    ##   # ... with 1 more columns
    ## )
    ## See spec(...) for full column specifications.

``` r
#Omit NA values
sol_train <- na.omit(sol_train)

sol_test <- na.omit(sol_test)
```

Part A: Linear model fitting & finding MSE
------------------------------------------

``` r
set.seed(1)
sol_fit1 = lm(Solubility~., data = sol_train)

summary(sol_fit1)
```

    ## 
    ## Call:
    ## lm(formula = Solubility ~ ., data = sol_train)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.75620 -0.28304  0.01165  0.30030  1.54887 
    ## 
    ## Coefficients:
    ##                     Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)        2.431e+00  2.162e+00   1.124 0.261303    
    ## FP001              3.594e-01  3.185e-01   1.128 0.259635    
    ## FP002              1.456e-01  2.637e-01   0.552 0.580960    
    ## FP003             -3.969e-02  1.314e-01  -0.302 0.762617    
    ## FP004             -3.049e-01  1.371e-01  -2.223 0.026520 *  
    ## FP005              2.837e+00  9.598e-01   2.956 0.003223 ** 
    ## FP006             -6.886e-02  2.041e-01  -0.337 0.735917    
    ## FP007              4.044e-02  1.152e-01   0.351 0.725643    
    ## FP008              1.121e-01  1.636e-01   0.685 0.493331    
    ## FP009             -8.242e-01  8.395e-01  -0.982 0.326536    
    ## FP010              4.193e-01  3.136e-01   1.337 0.181579    
    ## FP011              5.158e-02  2.198e-01   0.235 0.814503    
    ## FP012             -1.346e-02  1.611e-01  -0.084 0.933452    
    ## FP013             -4.519e-01  5.473e-01  -0.826 0.409311    
    ## FP014              3.281e-01  4.550e-01   0.721 0.471044    
    ## FP015             -1.839e-01  1.521e-01  -1.209 0.226971    
    ## FP016             -1.367e-01  1.548e-01  -0.883 0.377340    
    ## FP017             -1.704e-01  1.386e-01  -1.230 0.219187    
    ## FP018             -3.824e-01  2.388e-01  -1.602 0.109655    
    ## FP019             -3.131e-01  3.863e-01  -0.811 0.417862    
    ## FP020              2.072e-01  2.135e-01   0.971 0.332078    
    ## FP021             -5.956e-02  2.632e-01  -0.226 0.821060    
    ## FP022              2.336e-01  3.456e-01   0.676 0.499180    
    ## FP023             -3.193e-01  1.909e-01  -1.672 0.094866 .  
    ## FP024             -4.272e-01  2.827e-01  -1.511 0.131162    
    ## FP025              4.376e-01  4.538e-01   0.964 0.335184    
    ## FP026              2.068e-01  2.564e-01   0.806 0.420273    
    ## FP027              2.424e-01  2.429e-01   0.998 0.318594    
    ## FP028              1.070e-01  1.200e-01   0.892 0.372547    
    ## FP029             -9.857e-02  2.199e-01  -0.448 0.654163    
    ## FP030             -2.361e-01  2.468e-01  -0.957 0.339048    
    ## FP031              8.690e-02  1.346e-01   0.646 0.518754    
    ## FP032             -1.204e+00  7.772e-01  -1.550 0.121628    
    ## FP033              5.766e-01  4.236e-01   1.361 0.173882    
    ## FP034             -1.794e-01  2.618e-01  -0.685 0.493486    
    ## FP035             -2.140e-01  1.704e-01  -1.256 0.209605    
    ## FP036              7.701e-02  1.657e-01   0.465 0.642133    
    ## FP037              1.098e-01  1.725e-01   0.636 0.524693    
    ## FP038              2.721e-01  1.888e-01   1.441 0.150030    
    ## FP039              2.011e-02  2.888e-01   0.070 0.944491    
    ## FP040              5.477e-01  1.890e-01   2.898 0.003873 ** 
    ## FP041             -4.265e-01  3.004e-01  -1.420 0.156143    
    ## FP042             -9.901e-01  7.078e-01  -1.399 0.162294    
    ## FP043             -3.725e-02  2.096e-01  -0.178 0.859011    
    ## FP044             -3.860e-01  2.184e-01  -1.768 0.077562 .  
    ## FP045              2.120e-01  1.299e-01   1.631 0.103238    
    ## FP046             -3.504e-02  2.733e-01  -0.128 0.898010    
    ## FP047             -1.675e-02  1.414e-01  -0.118 0.905775    
    ## FP048              2.610e-01  2.434e-01   1.073 0.283810    
    ## FP049              1.241e-01  1.971e-01   0.630 0.529036    
    ## FP050              9.087e-03  1.410e-01   0.064 0.948648    
    ## FP051              1.050e-01  2.014e-01   0.521 0.602210    
    ## FP052             -4.569e-01  2.482e-01  -1.841 0.066029 .  
    ## FP053              2.994e-01  2.466e-01   1.214 0.225129    
    ## FP054              2.734e-02  1.829e-01   0.149 0.881229    
    ## FP055             -3.662e-01  1.970e-01  -1.858 0.063530 .  
    ## FP056             -2.961e-01  2.979e-01  -0.994 0.320541    
    ## FP057             -1.002e-01  1.379e-01  -0.727 0.467703    
    ## FP058              3.100e-01  8.074e-01   0.384 0.701129    
    ## FP059             -1.615e-01  1.690e-01  -0.956 0.339514    
    ## FP060              2.350e-01  1.474e-01   1.595 0.111209    
    ## FP061             -6.365e-01  1.440e-01  -4.421 1.13e-05 ***
    ## FP062             -5.224e-01  2.961e-01  -1.764 0.078078 .  
    ## FP063             -2.001e+00  1.287e+00  -1.554 0.120553    
    ## FP064              2.549e-01  1.221e-01   2.087 0.037207 *  
    ## FP065             -2.844e-01  1.197e-01  -2.377 0.017714 *  
    ## FP066              2.093e-01  1.264e-01   1.655 0.098301 .  
    ## FP067             -1.406e-01  1.540e-01  -0.913 0.361631    
    ## FP068              4.964e-01  2.028e-01   2.447 0.014630 *  
    ## FP069              1.324e-01  8.824e-02   1.501 0.133885    
    ## FP070              3.453e-03  8.088e-02   0.043 0.965963    
    ## FP071              1.474e-01  1.237e-01   1.192 0.233775    
    ## FP072             -9.773e-01  2.763e-01  -3.537 0.000431 ***
    ## FP073             -4.671e-01  2.072e-01  -2.254 0.024474 *  
    ## FP074              1.793e-01  1.206e-01   1.487 0.137566    
    ## FP075              1.231e-01  1.035e-01   1.188 0.235034    
    ## FP076              5.166e-01  1.704e-01   3.031 0.002525 ** 
    ## FP077              1.644e-01  1.236e-01   1.331 0.183739    
    ## FP078             -3.715e-01  1.588e-01  -2.339 0.019608 *  
    ## FP079              4.254e-01  1.881e-01   2.262 0.023992 *  
    ## FP080              3.101e-01  1.554e-01   1.996 0.046340 *  
    ## FP081             -3.208e-01  1.117e-01  -2.873 0.004192 ** 
    ## FP082              1.243e-01  9.524e-02   1.305 0.192379    
    ## FP083             -6.916e-01  2.134e-01  -3.241 0.001248 ** 
    ## FP084              3.626e-01  2.381e-01   1.523 0.128171    
    ## FP085             -3.310e-01  1.428e-01  -2.317 0.020785 *  
    ## FP086              1.169e-02  9.774e-02   0.120 0.904834    
    ## FP087              4.559e-02  2.797e-01   0.163 0.870568    
    ## FP088              2.416e-01  9.959e-02   2.425 0.015534 *  
    ## FP089              5.999e-01  2.320e-01   2.586 0.009915 ** 
    ## FP090             -2.450e-02  1.154e-01  -0.212 0.831930    
    ## FP091             -2.858e-01  3.185e-01  -0.897 0.369847    
    ## FP092              2.665e-01  2.069e-01   1.288 0.198156    
    ## FP093              1.974e-01  1.087e-01   1.816 0.069803 .  
    ## FP094             -1.991e-01  1.441e-01  -1.381 0.167707    
    ## FP095             -1.403e-01  1.124e-01  -1.248 0.212449    
    ## FP096             -5.024e-01  1.459e-01  -3.445 0.000605 ***
    ## FP097             -2.635e-01  1.666e-01  -1.582 0.114020    
    ## FP098             -2.865e-01  1.633e-01  -1.754 0.079863 .  
    ## FP099              2.592e-01  2.568e-01   1.009 0.313136    
    ## FP100             -4.008e-01  3.034e-01  -1.321 0.186949    
    ## FP101             -1.760e-01  3.019e-01  -0.583 0.560147    
    ## FP102              2.445e-01  3.449e-01   0.709 0.478579    
    ## FP103             -1.493e-01  9.148e-02  -1.632 0.103176    
    ## FP104             -1.428e-01  1.176e-01  -1.214 0.225238    
    ## FP105             -6.912e-02  1.395e-01  -0.495 0.620482    
    ## FP106              1.128e-01  1.288e-01   0.876 0.381495    
    ## FP107              2.778e+00  8.247e-01   3.369 0.000796 ***
    ## FP108              8.836e-03  1.852e-01   0.048 0.961970    
    ## FP109              8.200e-01  2.267e-01   3.617 0.000319 ***
    ## FP110              3.680e-01  3.311e-01   1.111 0.266811    
    ## FP111             -5.565e-01  1.420e-01  -3.918 9.80e-05 ***
    ## FP112             -1.079e-01  2.705e-01  -0.399 0.690108    
    ## FP113              1.511e-01  9.481e-02   1.594 0.111478    
    ## FP114             -1.201e-01  1.891e-01  -0.635 0.525628    
    ## FP115             -1.896e-01  1.405e-01  -1.349 0.177736    
    ## FP116              7.778e-03  1.897e-01   0.041 0.967300    
    ## FP117              2.583e-01  1.779e-01   1.452 0.147070    
    ## FP118             -1.964e-01  1.230e-01  -1.596 0.110940    
    ## FP119              7.515e-01  2.630e-01   2.857 0.004402 ** 
    ## FP120             -1.814e-01  1.794e-01  -1.011 0.312362    
    ## FP121             -4.731e-02  3.957e-01  -0.120 0.904866    
    ## FP122              1.048e-01  1.041e-01   1.007 0.314268    
    ## FP123              3.926e-02  1.765e-01   0.222 0.824066    
    ## FP124              1.235e-01  1.705e-01   0.724 0.469243    
    ## FP125             -2.633e-04  1.151e-01  -0.002 0.998175    
    ## FP126             -2.782e-01  1.177e-01  -2.363 0.018373 *  
    ## FP127             -6.123e-01  1.739e-01  -3.521 0.000457 ***
    ## FP128             -5.424e-01  1.932e-01  -2.807 0.005136 ** 
    ## FP129             -6.731e-02  2.243e-01  -0.300 0.764167    
    ## FP130             -1.034e+00  4.106e-01  -2.518 0.012009 *  
    ## FP131              2.158e-01  1.617e-01   1.335 0.182405    
    ## FP132             -1.976e-01  2.382e-01  -0.830 0.406998    
    ## FP133             -1.573e-01  1.217e-01  -1.293 0.196319    
    ## FP134              2.496e+00  1.196e+00   2.086 0.037310 *  
    ## FP135              1.818e-01  1.319e-01   1.379 0.168460    
    ## FP136             -7.763e-02  3.131e-01  -0.248 0.804237    
    ## FP137             -4.613e-02  2.978e-01  -0.155 0.876947    
    ## FP138             -9.392e-02  1.906e-01  -0.493 0.622251    
    ## FP139              7.659e-02  4.063e-01   0.189 0.850517    
    ## FP140              3.145e-01  2.149e-01   1.463 0.143784    
    ## FP141              2.219e-01  2.765e-01   0.802 0.422532    
    ## FP142              6.272e-01  1.488e-01   4.214 2.83e-05 ***
    ## FP143              9.981e-01  2.929e-01   3.407 0.000692 ***
    ## FP144              2.207e-01  2.839e-01   0.777 0.437195    
    ## FP145             -1.146e-01  1.188e-01  -0.964 0.335169    
    ## FP146             -2.324e-01  2.086e-01  -1.114 0.265716    
    ## FP147              1.502e-01  1.228e-01   1.223 0.221703    
    ## FP148             -1.600e-01  1.319e-01  -1.213 0.225560    
    ## FP149              1.172e-01  1.650e-01   0.710 0.477770    
    ## FP150              9.046e-02  1.577e-01   0.574 0.566368    
    ## FP151              2.899e-01  3.120e-01   0.929 0.353202    
    ## FP152             -2.544e-01  2.990e-01  -0.851 0.395087    
    ## FP153             -3.765e-01  2.773e-01  -1.358 0.175029    
    ## FP154             -1.027e+00  2.033e-01  -5.054 5.50e-07 ***
    ## FP155              4.888e-01  2.916e-01   1.676 0.094163 .  
    ## FP156             -3.602e-02  3.636e-01  -0.099 0.921109    
    ## FP157             -4.715e-01  2.468e-01  -1.910 0.056505 .  
    ## FP158              1.669e-02  1.925e-01   0.087 0.930943    
    ## FP159              1.800e-01  2.432e-01   0.740 0.459378    
    ## FP160              1.525e-02  2.177e-01   0.070 0.944155    
    ## FP161             -2.440e-01  1.433e-01  -1.703 0.089063 .  
    ## FP162              4.910e-02  1.859e-01   0.264 0.791710    
    ## FP163              4.785e-01  3.121e-01   1.533 0.125659    
    ## FP164              5.096e-01  1.899e-01   2.684 0.007446 ** 
    ## FP165              5.793e-01  2.146e-01   2.700 0.007103 ** 
    ## FP166             -6.582e-02  2.185e-01  -0.301 0.763293    
    ## FP167             -6.044e-01  2.515e-01  -2.403 0.016502 *  
    ## FP168             -1.187e-01  1.872e-01  -0.634 0.526173    
    ## FP169             -1.705e-01  8.312e-02  -2.051 0.040650 *  
    ## FP170             -7.902e-02  1.560e-01  -0.506 0.612745    
    ## FP171              4.651e-01  1.186e-01   3.922 9.64e-05 ***
    ## FP172             -4.426e-01  2.440e-01  -1.814 0.070120 .  
    ## FP173              4.243e-01  1.657e-01   2.561 0.010634 *  
    ## FP174             -1.010e-01  2.098e-01  -0.481 0.630311    
    ## FP175             -4.657e-02  2.481e-01  -0.188 0.851136    
    ## FP176              9.736e-01  2.644e-01   3.682 0.000249 ***
    ## FP177              1.386e-01  2.393e-01   0.579 0.562538    
    ## FP178              6.497e-02  2.079e-01   0.313 0.754691    
    ## FP179             -3.415e-02  2.232e-01  -0.153 0.878437    
    ## FP180             -7.905e-01  5.523e-01  -1.431 0.152839    
    ## FP181              4.925e-01  3.218e-01   1.531 0.126309    
    ## FP182             -1.124e-01  1.310e-01  -0.858 0.391384    
    ## FP183              2.998e-01  7.143e-01   0.420 0.674836    
    ## FP184              4.876e-01  1.580e-01   3.087 0.002103 ** 
    ## FP185             -3.778e-01  2.037e-01  -1.854 0.064108 .  
    ## FP186             -3.654e-01  1.953e-01  -1.871 0.061710 .  
    ## FP187              4.457e-01  2.682e-01   1.662 0.097015 .  
    ## FP188              1.475e-01  1.258e-01   1.172 0.241519    
    ## FP189             -1.984e-02  3.468e-01  -0.057 0.954384    
    ## FP190              2.629e-01  3.018e-01   0.871 0.383981    
    ## FP191              2.799e-01  1.465e-01   1.911 0.056388 .  
    ## FP192             -2.404e-01  2.751e-01  -0.874 0.382534    
    ## FP193              1.502e-01  1.494e-01   1.005 0.315159    
    ## FP194              8.029e-01  6.379e-01   1.259 0.208566    
    ## FP195              5.967e-02  3.435e-01   0.174 0.862158    
    ## FP196              1.091e-02  2.544e-01   0.043 0.965812    
    ## FP197             -3.736e-02  1.569e-01  -0.238 0.811793    
    ## FP198              1.896e-01  2.665e-01   0.712 0.476893    
    ## FP199             -9.932e-02  1.797e-01  -0.553 0.580702    
    ## FP200             -6.421e-02  2.161e-01  -0.297 0.766462    
    ## FP201             -4.838e-01  1.980e-01  -2.444 0.014771 *  
    ## FP202              5.664e-01  1.869e-01   3.031 0.002527 ** 
    ## FP203              2.586e-01  6.447e-01   0.401 0.688462    
    ## FP204             -1.371e-01  2.543e-01  -0.539 0.590008    
    ## FP205              7.177e-02  1.561e-01   0.460 0.645857    
    ## FP206             -6.769e-02  1.860e-01  -0.364 0.716094    
    ## FP207             -5.538e-03  2.060e-01  -0.027 0.978560    
    ## FP208             -5.338e-01  6.324e-01  -0.844 0.398925    
    ## MolWeight         -1.232e+00  2.296e-01  -5.365 1.09e-07 ***
    ## NumAtoms          -1.478e+01  3.473e+00  -4.257 2.35e-05 ***
    ## NumNonHAtoms       1.795e+01  3.166e+00   5.670 2.07e-08 ***
    ## NumBonds           9.843e+00  2.681e+00   3.671 0.000260 ***
    ## NumNonHBonds      -1.030e+01  1.793e+00  -5.746 1.35e-08 ***
    ## NumMultBonds       2.107e-01  1.754e-01   1.201 0.229990    
    ## NumRotBonds       -5.213e-01  1.334e-01  -3.908 0.000102 ***
    ## NumDblBonds       -7.492e-01  3.163e-01  -2.369 0.018111 *  
    ## NumAromaticBonds  -2.364e+00  6.232e-01  -3.794 0.000161 ***
    ## NumHydrogen        8.347e-01  1.880e-01   4.439 1.04e-05 ***
    ## NumCarbon          1.730e-02  3.763e-01   0.046 0.963335    
    ## NumNitrogen        6.125e+00  3.045e+00   2.011 0.044645 *  
    ## NumOxygen          2.389e+00  4.523e-01   5.283 1.69e-07 ***
    ## NumSulfer         -8.508e+00  3.619e+00  -2.351 0.018994 *  
    ## NumChlorine       -7.449e+00  1.989e+00  -3.744 0.000195 ***
    ## NumHalogen         1.408e+00  2.109e+00   0.668 0.504615    
    ## NumRings           1.276e+00  6.716e-01   1.901 0.057731 .  
    ## HydrophilicFactor  1.099e-02  1.137e-01   0.097 0.922998    
    ## SurfaceArea1       8.825e-02  6.058e-02   1.457 0.145643    
    ## SurfaceArea2       9.555e-02  5.615e-02   1.702 0.089208 .  
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.5524 on 722 degrees of freedom
    ## Multiple R-squared:  0.9446, Adjusted R-squared:  0.9271 
    ## F-statistic: 54.03 on 228 and 722 DF,  p-value: < 2.2e-16

``` r
sol_fit2 = predict(sol_fit1, data = sol_test)

MSE=mean((sol_test$Solubility-sol_fit2)^2)
```

    ## Warning in sol_test$Solubility - sol_fit2: longer object length is not a
    ## multiple of shorter object length

``` r
#Show MSE
print(MSE)
```

    ## [1] 8.915445

The model that was fit used all of the possible variables (228) in the sol\_train dataset, with Solubility as the outcome variable. MSE found using test data is 8.915445.

Part B: Ridge Regression
------------------------

``` r
# train data input matrix and response vector
xtrain = model.matrix(Solubility~.,sol_train)[,-1]
ytrain = sol_train$Solubility
#test data input matrix and response vector
xtest = model.matrix(Solubility~.,sol_test)[,-1]
ytest = sol_test$Solubility

#Using cross-validation to choose the tuning parameter 
set.seed (1)
cv.out = cv.glmnet(xtrain, ytrain, alpha=0)
plot(cv.out)
```

![](p8106_hw1_files/figure-markdown_github/unnamed-chunk-4-1.png)

``` r
bestlam1 = cv.out$lambda.min
#Creating training model using ridge regression
model1 = glmnet(xtrain, ytrain, alpha=0, lambda=bestlam1)
#Printing out the logistic model
model1$beta
```

    ## 228 x 1 sparse Matrix of class "dgCMatrix"
    ##                             s0
    ## FP001              0.048571563
    ## FP002              0.105273882
    ## FP003             -0.058142477
    ## FP004             -0.160657727
    ## FP005             -0.028606686
    ## FP006             -0.093014806
    ## FP007              0.043691748
    ## FP008              0.032209086
    ## FP009             -0.038234227
    ## FP010              0.044629726
    ## FP011              0.110590813
    ## FP012             -0.062208701
    ## FP013             -0.092181792
    ## FP014              0.001702610
    ## FP015             -0.033502127
    ## FP016             -0.116367554
    ## FP017             -0.182564355
    ## FP018             -0.152556213
    ## FP019              0.025153931
    ## FP020              0.114998192
    ## FP021              0.004961567
    ## FP022              0.148912625
    ## FP023             -0.166205869
    ## FP024             -0.112754629
    ## FP025              0.018268571
    ## FP026              0.172364845
    ## FP027              0.220977507
    ## FP028              0.073090237
    ## FP029             -0.053376081
    ## FP030             -0.158480321
    ## FP031              0.190265393
    ## FP032             -0.144034783
    ## FP033              0.307229808
    ## FP034             -0.181661114
    ## FP035             -0.137622878
    ## FP036             -0.013056806
    ## FP037              0.268364141
    ## FP038              0.134313133
    ## FP039             -0.420386400
    ## FP040              0.470222823
    ## FP041             -0.047852821
    ## FP042              0.057350141
    ## FP043              0.072733613
    ## FP044             -0.335211025
    ## FP045              0.111636264
    ## FP046              0.107715734
    ## FP047             -0.044694266
    ## FP048              0.025957129
    ## FP049              0.298301490
    ## FP050             -0.101835384
    ## FP051             -0.031109173
    ## FP052             -0.090088973
    ## FP053              0.326095569
    ## FP054             -0.098630503
    ## FP055             -0.165141407
    ## FP056             -0.056224964
    ## FP057             -0.110798069
    ## FP058              0.063585995
    ## FP059             -0.330881179
    ## FP060              0.100562606
    ## FP061             -0.069095204
    ## FP062              0.074948641
    ## FP063              0.229840685
    ## FP064              0.147545845
    ## FP065             -0.159340337
    ## FP066              0.119157551
    ## FP067             -0.090324812
    ## FP068              0.068069906
    ## FP069              0.142062269
    ## FP070             -0.195898859
    ## FP071              0.103504947
    ## FP072              0.298702045
    ## FP073             -0.088785701
    ## FP074              0.128697740
    ## FP075              0.232091352
    ## FP076              0.035603110
    ## FP077              0.091577347
    ## FP078             -0.032768936
    ## FP079              0.164942466
    ## FP080              0.107890756
    ## FP081             -0.179920416
    ## FP082              0.103922381
    ## FP083             -0.235012722
    ## FP084              0.201091576
    ## FP085             -0.271151039
    ## FP086             -0.073892194
    ## FP087              0.076786691
    ## FP088              0.138474028
    ## FP089             -0.126667663
    ## FP090             -0.044402097
    ## FP091              0.059308545
    ## FP092              0.023202187
    ## FP093              0.109961839
    ## FP094             -0.119851912
    ## FP095              0.042539475
    ## FP096              0.059838086
    ## FP097              0.115012261
    ## FP098             -0.060755766
    ## FP099              0.141388073
    ## FP100             -0.064107268
    ## FP101              0.115850694
    ## FP102              0.143337573
    ## FP103             -0.131200656
    ## FP104             -0.116354271
    ## FP105             -0.087529604
    ## FP106              0.004309220
    ## FP107             -0.002306478
    ## FP108              0.049304981
    ## FP109              0.255561286
    ## FP110              0.029642683
    ## FP111             -0.361837933
    ## FP112             -0.093473033
    ## FP113              0.084026880
    ## FP114              0.127794885
    ## FP115              0.132751940
    ## FP116              0.156733286
    ## FP117             -0.099859905
    ## FP118             -0.128803997
    ## FP119              0.211022895
    ## FP120             -0.056066071
    ## FP121             -0.085028928
    ## FP122              0.193909688
    ## FP123             -0.040324489
    ## FP124              0.238186405
    ## FP125              0.092593616
    ## FP126             -0.301731652
    ## FP127             -0.289110769
    ## FP128             -0.220485112
    ## FP129              0.057376962
    ## FP130             -0.227033171
    ## FP131              0.265725185
    ## FP132             -0.047002919
    ## FP133             -0.140779038
    ## FP134             -0.104003008
    ## FP135              0.183694562
    ## FP136              0.100707961
    ## FP137              0.078271501
    ## FP138              0.183324425
    ## FP139              0.033559905
    ## FP140              0.075098664
    ## FP141             -0.156518349
    ## FP142              0.346356785
    ## FP143              0.294702770
    ## FP144              0.021960398
    ## FP145             -0.203290472
    ## FP146             -0.086731737
    ## FP147              0.244151434
    ## FP148              0.002498031
    ## FP149             -0.016275542
    ## FP150              0.126637494
    ## FP151              0.125169669
    ## FP152             -0.019287628
    ## FP153             -0.105337062
    ## FP154             -0.332900919
    ## FP155              0.146314592
    ## FP156             -0.218556027
    ## FP157              0.036380538
    ## FP158             -0.050341555
    ## FP159              0.257692975
    ## FP160             -0.131736412
    ## FP161             -0.058026604
    ## FP162              0.078421652
    ## FP163              0.220164101
    ## FP164              0.260844553
    ## FP165             -0.028289430
    ## FP166              0.101182077
    ## FP167             -0.123735498
    ## FP168             -0.127565710
    ## FP169             -0.157691985
    ## FP170              0.058155386
    ## FP171              0.231493254
    ## FP172             -0.308700640
    ## FP173              0.318826607
    ## FP174             -0.106410744
    ## FP175             -0.029643445
    ## FP176              0.306586690
    ## FP177             -0.025688832
    ## FP178             -0.009298311
    ## FP179              0.071739314
    ## FP180             -0.115412087
    ## FP181              0.103836745
    ## FP182             -0.043091377
    ## FP183             -0.028900515
    ## FP184              0.261802285
    ## FP185             -0.060114789
    ## FP186             -0.221781913
    ## FP187              0.146852340
    ## FP188              0.246491529
    ## FP189              0.034353769
    ## FP190              0.191409521
    ## FP191              0.085721390
    ## FP192              0.056799355
    ## FP193             -0.077454152
    ## FP194              0.015649164
    ## FP195             -0.063399497
    ## FP196              0.087236164
    ## FP197              0.011136145
    ## FP198              0.212185374
    ## FP199             -0.005965323
    ## FP200             -0.074680414
    ## FP201             -0.278599469
    ## FP202              0.233727435
    ## FP203              0.053488928
    ## FP204             -0.076704629
    ## FP205             -0.119039583
    ## FP206             -0.092024292
    ## FP207             -0.036395459
    ## FP208              0.001400338
    ## MolWeight         -1.076259915
    ## NumAtoms          -0.378851149
    ## NumNonHAtoms      -0.644930191
    ## NumBonds          -0.353127016
    ## NumNonHBonds      -0.340794348
    ## NumMultBonds      -0.100612602
    ## NumRotBonds       -0.190359919
    ## NumDblBonds       -0.065111782
    ## NumAromaticBonds  -0.127098158
    ## NumHydrogen        0.080318847
    ## NumCarbon         -0.266496463
    ## NumNitrogen        0.317889186
    ## NumOxygen          0.336467847
    ## NumSulfer         -0.614537357
    ## NumChlorine       -0.662538522
    ## NumHalogen        -0.516545625
    ## NumRings          -0.297982934
    ## HydrophilicFactor  0.125788887
    ## SurfaceArea1       0.077557458
    ## SurfaceArea2       0.049227852

``` r
#Fitting training model on test set
pred1 = predict(model1, s=bestlam1, newx=xtest)
#Calculating Accuracy
MSE1 = mean((pred1-ytest)^2)
print(MSE1)
```

    ## [1] 0.5147447

The MSE from the ridge regression model is 0.5559241.

Part C: Lasso
-------------

``` r
set.seed (1)
cv.out2 = cv.glmnet(xtrain, ytrain, alpha = 1)
plot(cv.out2)
```

![](p8106_hw1_files/figure-markdown_github/unnamed-chunk-6-1.png)

``` r
bestlam2 = cv.out2$lambda.min
#Creating training model using lasso regression
model2 = glmnet(xtrain, ytrain, alpha=1, lambda=bestlam2)
#Printing out the logistic model
model2$beta
```

    ## 228 x 1 sparse Matrix of class "dgCMatrix"
    ##                              s0
    ## FP001              .           
    ## FP002              0.2315515400
    ## FP003             -0.0452700172
    ## FP004             -0.2284576798
    ## FP005              .           
    ## FP006             -0.0550329862
    ## FP007              .           
    ## FP008              .           
    ## FP009              .           
    ## FP010              .           
    ## FP011              .           
    ## FP012             -0.0488610209
    ## FP013             -0.0398712343
    ## FP014              .           
    ## FP015             -0.0844556340
    ## FP016             -0.0808159737
    ## FP017             -0.1321821552
    ## FP018             -0.0943973931
    ## FP019              .           
    ## FP020              0.0756695947
    ## FP021              .           
    ## FP022              .           
    ## FP023             -0.1448831354
    ## FP024             -0.1135649923
    ## FP025              .           
    ## FP026              0.2544955376
    ## FP027              0.2907938475
    ## FP028              .           
    ## FP029              .           
    ## FP030             -0.1574349064
    ## FP031              0.1219790391
    ## FP032              .           
    ## FP033              0.1130425508
    ## FP034             -0.0145873016
    ## FP035             -0.1267207759
    ## FP036              .           
    ## FP037              0.2177979614
    ## FP038              0.0578172904
    ## FP039             -0.4290921657
    ## FP040              0.4361045653
    ## FP041              .           
    ## FP042              .           
    ## FP043              0.0393624025
    ## FP044             -0.2981133957
    ## FP045              0.0816641412
    ## FP046              .           
    ## FP047              .           
    ## FP048              .           
    ## FP049              0.2922687115
    ## FP050             -0.1509272798
    ## FP051              .           
    ## FP052              .           
    ## FP053              0.2088902702
    ## FP054             -0.0955642628
    ## FP055             -0.1393337999
    ## FP056              .           
    ## FP057             -0.0858003724
    ## FP058              .           
    ## FP059             -0.2859797059
    ## FP060              .           
    ## FP061             -0.1652977360
    ## FP062              .           
    ## FP063              .           
    ## FP064              0.2501102213
    ## FP065             -0.1444401241
    ## FP066              0.0502835110
    ## FP067              .           
    ## FP068              .           
    ## FP069              0.1351903042
    ## FP070             -0.0832582157
    ## FP071              0.1066453538
    ## FP072              .           
    ## FP073             -0.1103129622
    ## FP074              0.1051572952
    ## FP075              0.1819081709
    ## FP076              0.1859741155
    ## FP077              0.0877822766
    ## FP078             -0.1327069383
    ## FP079              0.2302350121
    ## FP080              0.0001751039
    ## FP081             -0.1988294140
    ## FP082              0.1410496629
    ## FP083             -0.3437062020
    ## FP084              0.2652059306
    ## FP085             -0.3288613993
    ## FP086             -0.0160542582
    ## FP087              .           
    ## FP088              0.0929715900
    ## FP089              .           
    ## FP090              .           
    ## FP091              .           
    ## FP092              .           
    ## FP093              0.1433953436
    ## FP094             -0.1592074664
    ## FP095              .           
    ## FP096             -0.0535040874
    ## FP097              .           
    ## FP098             -0.0469648950
    ## FP099              0.1932737423
    ## FP100              .           
    ## FP101              .           
    ## FP102              0.0205898175
    ## FP103             -0.1111175220
    ## FP104             -0.0800806277
    ## FP105             -0.0495838735
    ## FP106              0.0662775213
    ## FP107              .           
    ## FP108              .           
    ## FP109              0.3266785736
    ## FP110              .           
    ## FP111             -0.3785220892
    ## FP112              .           
    ## FP113              0.1085857120
    ## FP114              .           
    ## FP115              .           
    ## FP116              0.0158784420
    ## FP117              .           
    ## FP118             -0.0912497552
    ## FP119              0.2125230842
    ## FP120             -0.0064473630
    ## FP121              .           
    ## FP122              0.1972309341
    ## FP123              .           
    ## FP124              0.3034421045
    ## FP125              0.0481089919
    ## FP126             -0.1610618224
    ## FP127             -0.5077304087
    ## FP128             -0.2376981443
    ## FP129              .           
    ## FP130             -0.3045219054
    ## FP131              0.1693807431
    ## FP132             -0.0274348110
    ## FP133             -0.1539694397
    ## FP134              .           
    ## FP135              0.1820067389
    ## FP136              .           
    ## FP137              0.1927047428
    ## FP138              0.2219350521
    ## FP139              .           
    ## FP140              0.0301058703
    ## FP141             -0.0926856980
    ## FP142              0.4564709016
    ## FP143              0.3134339939
    ## FP144              .           
    ## FP145             -0.0787157089
    ## FP146              .           
    ## FP147              0.1481059183
    ## FP148             -0.0471945908
    ## FP149              .           
    ## FP150              0.0142143169
    ## FP151              .           
    ## FP152              .           
    ## FP153              .           
    ## FP154             -0.5046370779
    ## FP155              0.0254389729
    ## FP156             -0.2334311159
    ## FP157             -0.0539547887
    ## FP158              .           
    ## FP159              0.0714027416
    ## FP160             -0.0448203765
    ## FP161             -0.0706143773
    ## FP162              .           
    ## FP163              0.1767192888
    ## FP164              0.3753459301
    ## FP165              .           
    ## FP166              0.0216510071
    ## FP167             -0.1013793437
    ## FP168              .           
    ## FP169             -0.1446048446
    ## FP170              0.0243618691
    ## FP171              0.2512944049
    ## FP172             -0.5292029715
    ## FP173              0.3503781364
    ## FP174             -0.1072265989
    ## FP175              .           
    ## FP176              0.3943065443
    ## FP177              .           
    ## FP178              .           
    ## FP179              .           
    ## FP180             -0.0787435508
    ## FP181              0.1682588070
    ## FP182             -0.0241142925
    ## FP183              .           
    ## FP184              0.2997547902
    ## FP185              .           
    ## FP186             -0.1904668811
    ## FP187              0.1818630016
    ## FP188              0.2033718684
    ## FP189              .           
    ## FP190              0.2969760085
    ## FP191              0.0720463019
    ## FP192              0.0492821168
    ## FP193              .           
    ## FP194              .           
    ## FP195              .           
    ## FP196              .           
    ## FP197              .           
    ## FP198              0.1544564975
    ## FP199              .           
    ## FP200              .           
    ## FP201             -0.2924936626
    ## FP202              0.4115175239
    ## FP203              0.0750737499
    ## FP204              .           
    ## FP205              .           
    ## FP206             -0.0580464859
    ## FP207              .           
    ## FP208              .           
    ## MolWeight         -1.4101748230
    ## NumAtoms          -0.3069097746
    ## NumNonHAtoms       .           
    ## NumBonds           .           
    ## NumNonHBonds      -0.6963002088
    ## NumMultBonds      -0.1290204640
    ## NumRotBonds       -0.2527035549
    ## NumDblBonds        .           
    ## NumAromaticBonds  -0.0822529444
    ## NumHydrogen        0.1812076671
    ## NumCarbon         -0.7263615672
    ## NumNitrogen        0.4734007185
    ## NumOxygen          0.5407810898
    ## NumSulfer         -0.2651673465
    ## NumChlorine       -0.6176745934
    ## NumHalogen         .           
    ## NumRings          -0.1721595218
    ## HydrophilicFactor  .           
    ## SurfaceArea1       0.2379255339
    ## SurfaceArea2       .

There are 141 nonzero predictors in the model.

``` r
#Fitting training model on test set
pred2 = predict(model2, s=bestlam2, newx=xtest)
#Calculating Accuracy
MSE2=mean((pred2-ytest)^2)
#Printing MSE
print(MSE2)
```

    ## [1] 0.4952673

The MSE of the lasso model is 0.4952673.

``` r
#Retrieving the lasso coefficients
lasscoef=predict(model2, type="coefficients", s=bestlam2)[1:length(model2$beta),]
#Printing non zero coefficients
lasscoef[lasscoef!=0]
```

    ##      (Intercept)            FP002            FP003            FP004 
    ##     7.7958826494     0.2315515400    -0.0452700172    -0.2284576798 
    ##            FP006            FP012            FP013            FP015 
    ##    -0.0550329862    -0.0488610209    -0.0398712343    -0.0844556340 
    ##            FP016            FP017            FP018            FP020 
    ##    -0.0808159737    -0.1321821552    -0.0943973931     0.0756695947 
    ##            FP023            FP024            FP026            FP027 
    ##    -0.1448831354    -0.1135649923     0.2544955376     0.2907938475 
    ##            FP030            FP031            FP033            FP034 
    ##    -0.1574349064     0.1219790391     0.1130425508    -0.0145873016 
    ##            FP035            FP037            FP038            FP039 
    ##    -0.1267207759     0.2177979614     0.0578172904    -0.4290921657 
    ##            FP040            FP043            FP044            FP045 
    ##     0.4361045653     0.0393624025    -0.2981133957     0.0816641412 
    ##            FP049            FP050            FP053            FP054 
    ##     0.2922687115    -0.1509272798     0.2088902702    -0.0955642628 
    ##            FP055            FP057            FP059            FP061 
    ##    -0.1393337999    -0.0858003724    -0.2859797059    -0.1652977360 
    ##            FP064            FP065            FP066            FP069 
    ##     0.2501102213    -0.1444401241     0.0502835110     0.1351903042 
    ##            FP070            FP071            FP073            FP074 
    ##    -0.0832582157     0.1066453538    -0.1103129622     0.1051572952 
    ##            FP075            FP076            FP077            FP078 
    ##     0.1819081709     0.1859741155     0.0877822766    -0.1327069383 
    ##            FP079            FP080            FP081            FP082 
    ##     0.2302350121     0.0001751039    -0.1988294140     0.1410496629 
    ##            FP083            FP084            FP085            FP086 
    ##    -0.3437062020     0.2652059306    -0.3288613993    -0.0160542582 
    ##            FP088            FP093            FP094            FP096 
    ##     0.0929715900     0.1433953436    -0.1592074664    -0.0535040874 
    ##            FP098            FP099            FP102            FP103 
    ##    -0.0469648950     0.1932737423     0.0205898175    -0.1111175220 
    ##            FP104            FP105            FP106            FP109 
    ##    -0.0800806277    -0.0495838735     0.0662775213     0.3266785736 
    ##            FP111            FP113            FP116            FP118 
    ##    -0.3785220892     0.1085857120     0.0158784420    -0.0912497552 
    ##            FP119            FP120            FP122            FP124 
    ##     0.2125230842    -0.0064473630     0.1972309341     0.3034421045 
    ##            FP125            FP126            FP127            FP128 
    ##     0.0481089919    -0.1610618224    -0.5077304087    -0.2376981443 
    ##            FP130            FP131            FP132            FP133 
    ##    -0.3045219054     0.1693807431    -0.0274348110    -0.1539694397 
    ##            FP135            FP137            FP138            FP140 
    ##     0.1820067389     0.1927047428     0.2219350521     0.0301058703 
    ##            FP141            FP142            FP143            FP145 
    ##    -0.0926856980     0.4564709016     0.3134339939    -0.0787157089 
    ##            FP147            FP148            FP150            FP154 
    ##     0.1481059183    -0.0471945908     0.0142143169    -0.5046370779 
    ##            FP155            FP156            FP157            FP159 
    ##     0.0254389729    -0.2334311159    -0.0539547887     0.0714027416 
    ##            FP160            FP161            FP163            FP164 
    ##    -0.0448203765    -0.0706143773     0.1767192888     0.3753459301 
    ##            FP166            FP167            FP169            FP170 
    ##     0.0216510071    -0.1013793437    -0.1446048446     0.0243618691 
    ##            FP171            FP172            FP173            FP174 
    ##     0.2512944049    -0.5292029715     0.3503781364    -0.1072265989 
    ##            FP176            FP180            FP181            FP182 
    ##     0.3943065443    -0.0787435508     0.1682588070    -0.0241142925 
    ##            FP184            FP186            FP187            FP188 
    ##     0.2997547902    -0.1904668811     0.1818630016     0.2033718684 
    ##            FP190            FP191            FP192            FP198 
    ##     0.2969760085     0.0720463019     0.0492821168     0.1544564975 
    ##            FP201            FP202            FP203            FP206 
    ##    -0.2924936626     0.4115175239     0.0750737499    -0.0580464859 
    ##        MolWeight         NumAtoms     NumNonHBonds     NumMultBonds 
    ##    -1.4101748230    -0.3069097746    -0.6963002088    -0.1290204640 
    ##      NumRotBonds NumAromaticBonds      NumHydrogen        NumCarbon 
    ##    -0.2527035549    -0.0822529444     0.1812076671    -0.7263615672 
    ##      NumNitrogen        NumOxygen        NumSulfer      NumChlorine 
    ##     0.4734007185     0.5407810898    -0.2651673465    -0.6176745934 
    ##         NumRings     SurfaceArea1 
    ##    -0.1721595218     0.2379255339

Part D: PCR Model
-----------------

``` r
set.seed(1)
pcr.fit = pcr(Solubility~., data = sol_train, scale=TRUE, validation="CV")
summary(pcr.fit)
```

    ## Data:    X dimension: 951 228 
    ##  Y dimension: 951 1
    ## Fit method: svdpc
    ## Number of components considered: 228
    ## 
    ## VALIDATION: RMSEP
    ## Cross-validated using 10 random segments.
    ##        (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
    ## CV           2.048    2.041    1.979    1.715    1.605    1.565    1.445
    ## adjCV        2.048    2.041    1.979    1.714    1.600    1.595    1.444
    ##        7 comps  8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
    ## CV       1.292    1.290    1.292     1.267     1.244     1.243     1.244
    ## adjCV    1.289    1.288    1.291     1.266     1.240     1.242     1.243
    ##        14 comps  15 comps  16 comps  17 comps  18 comps  19 comps
    ## CV        1.194     1.169     1.111     1.053     1.049     1.034
    ## adjCV     1.193     1.168     1.107     1.048     1.047     1.032
    ##        20 comps  21 comps  22 comps  23 comps  24 comps  25 comps
    ## CV        1.012     1.006     1.003    0.9745    0.9736    0.9732
    ## adjCV     1.010     1.004     1.006    0.9716    0.9716    0.9720
    ##        26 comps  27 comps  28 comps  29 comps  30 comps  31 comps
    ## CV       0.9673    0.9613    0.9580    0.9589    0.9588    0.9449
    ## adjCV    0.9630    0.9594    0.9568    0.9575    0.9585    0.9379
    ##        32 comps  33 comps  34 comps  35 comps  36 comps  37 comps
    ## CV       0.9302    0.9188    0.9174    0.9017    0.8915    0.8842
    ## adjCV    0.9291    0.9156    0.9157    0.8998    0.8890    0.8804
    ##        38 comps  39 comps  40 comps  41 comps  42 comps  43 comps
    ## CV       0.8846    0.8801    0.8732    0.8711    0.8716    0.8696
    ## adjCV    0.8823    0.8799    0.8685    0.8679    0.8713    0.8706
    ##        44 comps  45 comps  46 comps  47 comps  48 comps  49 comps
    ## CV       0.8542    0.8492    0.8441    0.8385    0.8398    0.8420
    ## adjCV    0.8488    0.8445    0.8424    0.8352    0.8375    0.8392
    ##        50 comps  51 comps  52 comps  53 comps  54 comps  55 comps
    ## CV       0.8364    0.8334    0.8283    0.8281    0.8279    0.8303
    ## adjCV    0.8377    0.8312    0.8249    0.8250    0.8255    0.8280
    ##        56 comps  57 comps  58 comps  59 comps  60 comps  61 comps
    ## CV       0.8290    0.8276    0.8212    0.8206    0.8244    0.8125
    ## adjCV    0.8274    0.8273    0.8238    0.8200    0.8219    0.8058
    ##        62 comps  63 comps  64 comps  65 comps  66 comps  67 comps
    ## CV       0.8063    0.8092    0.8070    0.8063    0.8088    0.8068
    ## adjCV    0.8012    0.8051    0.8036    0.8038    0.8065    0.8028
    ##        68 comps  69 comps  70 comps  71 comps  72 comps  73 comps
    ## CV       0.8069    0.8065    0.8077    0.8023    0.7965    0.7945
    ## adjCV    0.8040    0.8032    0.8061    0.8029    0.7908    0.7895
    ##        74 comps  75 comps  76 comps  77 comps  78 comps  79 comps
    ## CV       0.7962    0.7943    0.7956    0.7976    0.7960    0.7935
    ## adjCV    0.7920    0.7906    0.7915    0.7945    0.7929    0.7892
    ##        80 comps  81 comps  82 comps  83 comps  84 comps  85 comps
    ## CV       0.7940    0.7951    0.7924    0.7917    0.7916    0.7873
    ## adjCV    0.7912    0.7918    0.7882    0.7883    0.7884    0.7831
    ##        86 comps  87 comps  88 comps  89 comps  90 comps  91 comps
    ## CV       0.7876    0.7887    0.7900    0.7902    0.7899    0.7861
    ## adjCV    0.7836    0.7850    0.7873    0.7888    0.7874    0.7814
    ##        92 comps  93 comps  94 comps  95 comps  96 comps  97 comps
    ## CV       0.7816    0.7783    0.7765    0.7778    0.7789    0.7795
    ## adjCV    0.7742    0.7714    0.7705    0.7721    0.7737    0.7756
    ##        98 comps  99 comps  100 comps  101 comps  102 comps  103 comps
    ## CV       0.7808    0.7781     0.7732     0.7708     0.7728     0.7714
    ## adjCV    0.7772    0.7758     0.7677     0.7662     0.7684     0.7676
    ##        104 comps  105 comps  106 comps  107 comps  108 comps  109 comps
    ## CV        0.7698     0.7677     0.7688     0.7701     0.7703     0.7707
    ## adjCV     0.7631     0.7616     0.7641     0.7663     0.7677     0.7629
    ##        110 comps  111 comps  112 comps  113 comps  114 comps  115 comps
    ## CV        0.7700     0.7672     0.7623     0.7604     0.7604     0.7580
    ## adjCV     0.7642     0.7624     0.7593     0.7556     0.7553     0.7553
    ##        116 comps  117 comps  118 comps  119 comps  120 comps  121 comps
    ## CV        0.7588     0.7581     0.7584     0.7571     0.7510     0.7523
    ## adjCV     0.7554     0.7558     0.7578     0.7550     0.7504     0.7468
    ##        122 comps  123 comps  124 comps  125 comps  126 comps  127 comps
    ## CV        0.7460     0.7459     0.7452     0.7433     0.7458     0.7468
    ## adjCV     0.7427     0.7408     0.7414     0.7362     0.7394     0.7416
    ##        128 comps  129 comps  130 comps  131 comps  132 comps  133 comps
    ## CV        0.7459     0.7417     0.7408     0.7363     0.7326     0.7321
    ## adjCV     0.7423     0.7372     0.7385     0.7275     0.7232     0.7244
    ##        134 comps  135 comps  136 comps  137 comps  138 comps  139 comps
    ## CV        0.7285     0.7280     0.7270     0.7275     0.7295     0.7301
    ## adjCV     0.7226     0.7229     0.7204     0.7202     0.7227     0.7242
    ##        140 comps  141 comps  142 comps  143 comps  144 comps  145 comps
    ## CV        0.7244     0.7187     0.7177     0.7191     0.7160     0.7167
    ## adjCV     0.7186     0.7124     0.7129     0.7166     0.7083     0.7098
    ##        146 comps  147 comps  148 comps  149 comps  150 comps  151 comps
    ## CV        0.7160     0.7097     0.7079     0.7075     0.7054     0.7066
    ## adjCV     0.7086     0.7039     0.7000     0.7003     0.6977     0.6992
    ##        152 comps  153 comps  154 comps  155 comps  156 comps  157 comps
    ## CV        0.7087     0.7101     0.7071     0.7089     0.7123     0.7081
    ## adjCV     0.7020     0.7034     0.7014     0.7014     0.7054     0.6998
    ##        158 comps  159 comps  160 comps  161 comps  162 comps  163 comps
    ## CV        0.7071     0.7093     0.7093     0.7081     0.7113     0.7135
    ## adjCV     0.6985     0.7013     0.7015     0.7001     0.7038     0.7067
    ##        164 comps  165 comps  166 comps  167 comps  168 comps  169 comps
    ## CV        0.7140     0.7153     0.7146     0.7126     0.7135     0.7141
    ## adjCV     0.7059     0.7079     0.7062     0.7047     0.7053     0.7061
    ##        170 comps  171 comps  172 comps  173 comps  174 comps  175 comps
    ## CV        0.7176     0.7187     0.7195     0.7184     0.7195     0.7209
    ## adjCV     0.7093     0.7103     0.7115     0.7108     0.7109     0.7123
    ##        176 comps  177 comps  178 comps  179 comps  180 comps  181 comps
    ## CV        0.7215     0.7236     0.7228     0.7217     0.7184     0.7206
    ## adjCV     0.7119     0.7141     0.7139     0.7124     0.7100     0.7113
    ##        182 comps  183 comps  184 comps  185 comps  186 comps  187 comps
    ## CV        0.7254     0.7245     0.7211     0.7227     0.7204     0.7192
    ## adjCV     0.7165     0.7149     0.7119     0.7137     0.7103     0.7093
    ##        188 comps  189 comps  190 comps  191 comps  192 comps  193 comps
    ## CV        0.7216     0.7215     0.7222     0.7253     0.7265     0.7232
    ## adjCV     0.7118     0.7113     0.7118     0.7151     0.7168     0.7145
    ##        194 comps  195 comps  196 comps  197 comps  198 comps  199 comps
    ## CV        0.7222     0.7232     0.7232     0.7261     0.7244     0.7298
    ## adjCV     0.7128     0.7145     0.7118     0.7153     0.7148     0.7205
    ##        200 comps  201 comps  202 comps  203 comps  204 comps  205 comps
    ## CV        0.7341      0.739     0.7360     0.7348     0.7341     0.7351
    ## adjCV     0.7230      0.728     0.7244     0.7236     0.7236     0.7240
    ##        206 comps  207 comps  208 comps  209 comps  210 comps  211 comps
    ## CV        0.7339     0.7403     0.7321     0.7336     0.7369     0.7407
    ## adjCV     0.7218     0.7286     0.7199     0.7213     0.7245     0.7282
    ##        212 comps  213 comps  214 comps  215 comps  216 comps  217 comps
    ## CV        0.7383     0.7444     0.7445     0.7413     0.7360     0.7409
    ## adjCV     0.7258     0.7318     0.7315     0.7286     0.7238     0.7270
    ##        218 comps  219 comps  220 comps  221 comps  222 comps  223 comps
    ## CV        0.7379     0.7396     0.7400     0.7441     0.7401     0.7440
    ## adjCV     0.7246     0.7263     0.7269     0.7310     0.7272     0.7302
    ##        224 comps  225 comps  226 comps  227 comps  228 comps
    ## CV        0.7403     0.7391     0.7420     0.7401  1.113e+12
    ## adjCV     0.7273     0.7253     0.7281     0.7278  1.056e+12
    ## 
    ## TRAINING: % variance explained
    ##             1 comps  2 comps  3 comps  4 comps  5 comps  6 comps  7 comps
    ## X            12.417   23.083    30.29    34.91    39.27    43.53    46.98
    ## Solubility    0.734    7.182    30.52    39.36    39.52    50.82    60.83
    ##             8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
    ## X             50.08    53.04     55.46     57.67     59.81     61.72
    ## Solubility    61.00    61.01     62.57     64.10     64.17     64.36
    ##             14 comps  15 comps  16 comps  17 comps  18 comps  19 comps
    ## X              63.43     64.82     66.16     67.40     68.58     69.68
    ## Solubility     67.12     68.79     71.69     74.75     74.96     75.59
    ##             20 comps  21 comps  22 comps  23 comps  24 comps  25 comps
    ## X              70.73     71.76     72.72     73.64     74.48     75.31
    ## Solubility     76.72     76.96     77.00     78.34     78.40     78.48
    ##             26 comps  27 comps  28 comps  29 comps  30 comps  31 comps
    ## X              76.09     76.85     77.57     78.29     78.95     79.59
    ## Solubility     78.97     79.03     79.20     79.42     79.43     80.34
    ##             32 comps  33 comps  34 comps  35 comps  36 comps  37 comps
    ## X              80.22     80.81     81.38     81.92     82.46     82.96
    ## Solubility     80.94     81.52     81.53     82.15     82.66     82.96
    ##             38 comps  39 comps  40 comps  41 comps  42 comps  43 comps
    ## X              83.45     83.92     84.37     84.82     85.23     85.64
    ## Solubility     82.97     82.98     83.49     83.58     83.61     83.73
    ##             44 comps  45 comps  46 comps  47 comps  48 comps  49 comps
    ## X              86.03     86.42     86.78     87.13     87.46     87.77
    ## Solubility     84.41     84.54     84.56     84.82     84.82     84.93
    ##             50 comps  51 comps  52 comps  53 comps  54 comps  55 comps
    ## X              88.08     88.39     88.68     88.97     89.25     89.52
    ## Solubility     84.99     85.19     85.46     85.48     85.55     85.57
    ##             56 comps  57 comps  58 comps  59 comps  60 comps  61 comps
    ## X              89.77     90.02     90.26     90.51     90.75     90.97
    ## Solubility     85.61     85.62     85.70     85.89     86.12     86.61
    ##             62 comps  63 comps  64 comps  65 comps  66 comps  67 comps
    ## X              91.19     91.41     91.62     91.83     92.03     92.23
    ## Solubility     86.65     86.66     86.66     86.67     86.69     86.82
    ##             68 comps  69 comps  70 comps  71 comps  72 comps  73 comps
    ## X              92.42     92.60     92.77     92.95     93.12     93.28
    ## Solubility     86.83     86.92     86.94     87.00     87.45     87.48
    ##             74 comps  75 comps  76 comps  77 comps  78 comps  79 comps
    ## X              93.44     93.60     93.76     93.91     94.06     94.20
    ## Solubility     87.50     87.51     87.55     87.57     87.62     87.74
    ##             80 comps  81 comps  82 comps  83 comps  84 comps  85 comps
    ## X              94.34     94.47     94.61     94.74     94.86     94.99
    ## Solubility     87.76     87.83     87.95     87.95     88.00     88.11
    ##             86 comps  87 comps  88 comps  89 comps  90 comps  91 comps
    ## X              95.11     95.22     95.34     95.45     95.56     95.66
    ## Solubility     88.11     88.13     88.14     88.14     88.23     88.41
    ##             92 comps  93 comps  94 comps  95 comps  96 comps  97 comps
    ## X              95.77     95.87     95.97     96.07     96.16     96.26
    ## Solubility     88.60     88.67     88.68     88.71     88.72     88.72
    ##             98 comps  99 comps  100 comps  101 comps  102 comps  103 comps
    ## X              96.35     96.44      96.53      96.61      96.70      96.78
    ## Solubility     88.74     88.74      88.94      88.97      89.02      89.12
    ##             104 comps  105 comps  106 comps  107 comps  108 comps
    ## X               96.86      96.94      97.02      97.09      97.17
    ## Solubility      89.30      89.33      89.33      89.34      89.39
    ##             109 comps  110 comps  111 comps  112 comps  113 comps
    ## X               97.24      97.31      97.38      97.45      97.51
    ## Solubility      89.62      89.64      89.65      89.66      89.77
    ##             114 comps  115 comps  116 comps  117 comps  118 comps
    ## X               97.58      97.64      97.70      97.76      97.82
    ## Solubility      89.81      89.81      89.87      89.88      89.88
    ##             119 comps  120 comps  121 comps  122 comps  123 comps
    ## X               97.88      97.94      98.00      98.05      98.11
    ## Solubility      90.00      90.06      90.34      90.36      90.44
    ##             124 comps  125 comps  126 comps  127 comps  128 comps
    ## X               98.16      98.21      98.26      98.31      98.36
    ## Solubility      90.49      90.67      90.69      90.70      90.70
    ##             129 comps  130 comps  131 comps  132 comps  133 comps
    ## X               98.41      98.45      98.50      98.54      98.59
    ## Solubility      90.79      90.79      91.14      91.24      91.25
    ##             134 comps  135 comps  136 comps  137 comps  138 comps
    ## X               98.63      98.67      98.71      98.75      98.79
    ## Solubility      91.25      91.25      91.34      91.39      91.41
    ##             139 comps  140 comps  141 comps  142 comps  143 comps
    ## X               98.82      98.86      98.89      98.93      98.96
    ## Solubility      91.42      91.49      91.63      91.65      91.65
    ##             144 comps  145 comps  146 comps  147 comps  148 comps
    ## X               99.00      99.03      99.06      99.09      99.12
    ## Solubility      91.91      91.91      91.96      91.97      92.06
    ##             149 comps  150 comps  151 comps  152 comps  153 comps
    ## X               99.15      99.18      99.20      99.23      99.26
    ## Solubility      92.06      92.12      92.12      92.12      92.15
    ##             154 comps  155 comps  156 comps  157 comps  158 comps
    ## X               99.28      99.31      99.33      99.35      99.38
    ## Solubility      92.16      92.26      92.26      92.35      92.37
    ##             159 comps  160 comps  161 comps  162 comps  163 comps
    ## X               99.40      99.42      99.44      99.46      99.48
    ## Solubility      92.37      92.37      92.40      92.41      92.41
    ##             164 comps  165 comps  166 comps  167 comps  168 comps
    ## X               99.50      99.52      99.54      99.56      99.57
    ## Solubility      92.47      92.47      92.53      92.54      92.55
    ##             169 comps  170 comps  171 comps  172 comps  173 comps
    ## X               99.59      99.61      99.62      99.64      99.65
    ## Solubility      92.55      92.57      92.58      92.58      92.58
    ##             174 comps  175 comps  176 comps  177 comps  178 comps
    ## X               99.67      99.68       99.7      99.71      99.73
    ## Solubility      92.64      92.64       92.7      92.72      92.72
    ##             179 comps  180 comps  181 comps  182 comps  183 comps
    ## X               99.74      99.75      99.76      99.77      99.79
    ## Solubility      92.76      92.76      92.84      92.84      92.89
    ##             184 comps  185 comps  186 comps  187 comps  188 comps
    ## X                99.8      99.81      99.82      99.83      99.84
    ## Solubility       92.9      92.92      92.98      92.98      92.99
    ##             189 comps  190 comps  191 comps  192 comps  193 comps
    ## X               99.85      99.86      99.86      99.87      99.88
    ## Solubility      93.00      93.02      93.02      93.02      93.03
    ##             194 comps  195 comps  196 comps  197 comps  198 comps
    ## X               99.89      99.90      99.90      99.91      99.92
    ## Solubility      93.07      93.11      93.24      93.24      93.25
    ##             199 comps  200 comps  201 comps  202 comps  203 comps
    ## X               99.92      99.93      99.94      99.94      99.95
    ## Solubility      93.26      93.35      93.35      93.42      93.42
    ##             204 comps  205 comps  206 comps  207 comps  208 comps
    ## X               99.95      99.96      99.96      99.97      99.97
    ## Solubility      93.42      93.48      93.57      93.57      93.65
    ##             209 comps  210 comps  211 comps  212 comps  213 comps
    ## X               99.97      99.98      99.98      99.98      99.99
    ## Solubility      93.69      93.70      93.70      93.73      93.73
    ##             214 comps  215 comps  216 comps  217 comps  218 comps
    ## X               99.99      99.99      99.99      99.99      99.99
    ## Solubility      93.76      93.78      93.82      93.88      93.90
    ##             219 comps  220 comps  221 comps  222 comps  223 comps
    ## X              100.00     100.00     100.00     100.00     100.00
    ## Solubility      93.92      93.93      93.94      93.97      94.04
    ##             224 comps  225 comps  226 comps  227 comps  228 comps
    ## X              100.00     100.00     100.00     100.00     100.00
    ## Solubility      94.04      94.16      94.16      94.16      94.46

``` r
validationplot(pcr.fit, val.type="MSEP")
```

![](p8106_hw1_files/figure-markdown_github/unnamed-chunk-11-1.png)

``` r
pcr.pred = predict(pcr.fit, newdata = sol_test, ncomp=228)
mean((pcr.pred-ytest)^2)
```

    ## [1] 0.5558898

The MSE is 0.5558898, and the value of M is 228.

Part E: Conclusion
------------------

The Mean Squared Error from the Lasso regression model, 0.4952673, is the lowest out of the four models tested. Therefore, we should use this as the prediction model for Solubility.
